name: CI/CD

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          IMAGE_TAG="${GITHUB_REF##*/}-${{ github.run_number }}"
          docker build --pull --file=gateway/docker/production/nginx/Dockerfile --tag=${REGISTRY}/${IMAGE_NAME}-gateway:${IMAGE_TAG} gateway/docker
          docker build --pull --file=frontend/docker/production/nginx/Dockerfile --tag=${REGISTRY}/${IMAGE_NAME}-frontend:${IMAGE_TAG} frontend
          docker build --pull --file=api/docker/production/php-fpm/Dockerfile --tag=${REGISTRY}/${IMAGE_NAME}-api-php-fpm:${IMAGE_TAG} api
          docker build --pull --file=api/docker/production/nginx/Dockerfile --tag=${REGISTRY}/${IMAGE_NAME}-api:${IMAGE_TAG} api
          docker push ${REGISTRY}/${IMAGE_NAME}-gateway:${IMAGE_TAG}
          docker push ${REGISTRY}/${IMAGE_NAME}-frontend:${IMAGE_TAG}
          docker push ${REGISTRY}/${IMAGE_NAME}-api-php-fpm:${IMAGE_TAG}
          docker push ${REGISTRY}/${IMAGE_NAME}-api:${IMAGE_TAG}

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            IMAGE_TAG="${GITHUB_REF##*/}-${{ github.run_number }}"
            rm -rf site_${{ github.run_number }}
            mkdir site_${{ github.run_number }}
            cd site_${{ github.run_number }}
            echo "COMPOSE_PROJECT_NAME=auction" >> .env
            echo "REGISTRY=${{ env.REGISTRY }}/${{ github.repository }}" >> .env
            echo "IMAGE_TAG=${IMAGE_TAG}" >> .env
            wget https://raw.githubusercontent.com/${{ github.repository }}/${{ github.sha }}/docker-compose-production.yml
            docker-compose -f docker-compose-production.yml pull
            docker-compose -f docker-compose-production.yml down
            docker-compose -f docker-compose-production.yml up -d
            rm -f ../site
            ln -sr . ../site